project_id = "fwnkqcguvigyzlasexmr"

[functions.facebook-validate-token]
verify_jwt = false

[functions.facebook-add-profile]
verify_jwt = false

[functions.facebook-sync-accounts]
verify_jwt = false

[functions.facebook-delete-profile]
verify_jwt = false

[functions.facebook-update-proxy]
verify_jwt = false

[functions.facebook-sync-pixels]
verify_jwt = false

[functions.facebook-sync-pages]
verify_jwt = false

[functions.facebook-update-token]
verify_jwt = false

[functions.facebook-sync-catalogs]
verify_jwt = false

[functions.facebook-sync-product-sets]
verify_jwt = false

[functions.facebook-sync-business-managers]
verify_jwt = false

[functions.process-campaign-jobs]
verify_jwt = false

[functions.queue-processor]
verify_jwt = false

[functions.process-catalog-schedules]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.admin-impersonate]
verify_jwt = false

[functions.admin-search-users]
verify_jwt = false
